#!/bin/sh
#
# Set up environment variables for general build tool to operate
#
export ZOPEN_TYPE="TARBALL"
export ZOPEN_TARBALL_URL="https://ftp.wayne.edu/gnu/coreutils/coreutils-9.1.tar.gz"
export ZOPEN_TARBALL_DEPS="make gzip curl perl"
export ZOPEN_BOOTSTRAP="skip"
export ZOPEN_EXTRA_CPPFLAGS="-DSLOW_BUT_NO_HACKS=1 -DNO_ASM -qnose -I./,${PWD}/patches/PR2/include,${PWD}/coreutils-9.1/lib,/usr/include/le"
export ZOPEN_EXTRA_CFLAGS="-qnocsect"
export ZOPEN_EXTRA_CONFIGURE_OPTS="--disable-dependency-tracking"
